services:
  db:
    image: postgres:13
    env_file: ./db/.db.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dbback
    environment:
      - DB_HOST=db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432

  bot:
    build: ./bot
    networks:
      - dbback
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres"
    depends_on:
      db:
        condition: service_healthy

networks:
  dbback:
    driver: bridge

volumes:
  db_data:
